### ISSUE TITLE
Slicer custom app packaging issue with SlicerIGSIO

### ISSUE THREAD

**Issue by jamesobutler** [IGSIO/SlicerIGSIO#22]
I've observed in my Slicer custom application an issue with packaging due to SlicerIGSIO. I observed that in my "C:\MyCustomApp-build\Slicer-build\CPackConfig.cmake" that there was a vtkAddon section of `CPACK_INSTALL_CMAKE_PROJECTS` that when I removed it allow custom app packaging to not fail anymore. 

```cmake
set(CPACK_INSTALL_CMAKE_PROJECTS ";C:/SApp/IGSIO-build/inner-build;IGSIO;RuntimeLibraries;/;;vtkAddon;RuntimeLibraries;/;C:/SApp/OpenIGTLink-build;OpenIGTLink;RuntimeLibraries;/;C:/SApp/OpenIGTLinkIO-build;OpenIGTLinkIO;RuntimeLibraries;/;
```

Does vtkAddon runtime libraries actually need to be added as shown in the code below? Or is Slicer already including them with `Slicer_BUILD_vtkAddon` being on? Or is the vtkAddon_DIR not set appropriately as it appears to have been left blank in `CPACK_INSTALL_CMAKE_PROJECTS`?
https://github.com/IGSIO/SlicerIGSIO/blob/2601c3c491924084b1ac8e64e9c99abfa1d0942e/CMakeLists.txt#L73-L75

Related SlicerIGSIO commits regarding vtkAddon:
https://github.com/IGSIO/SlicerIGSIO/commit/fef9a392ef6c123442a675234e873cdc3d57e548 and https://github.com/IGSIO/SlicerIGSIO/commit/b0263b2f923220de68d90b8820d1d20de213ed42.

Slicer switched to vtkAddon as remote project in https://github.com/Slicer/Slicer/commit/aaf75e2aaa70a92f16b3ea544b7a8901a98cd509#.

cc: @Sunderlandkyl

**Comment by Sunderlandkyl** [comment]
I think it's a leftover from some previous configuration. Removed in https://github.com/IGSIO/SlicerIGSIO/commit/3e9991210ed74006eec92d79ac2bdbb5c41edd4f.
