### ISSUE TITLE
[Windows][VS22] Configuring fails

### ISSUE THREAD

**Issue by adamrankin** [IGSIO/SlicerIGSIO#28]
After building latest Slicer, configuring of inner project fails

```
CMake Error at C:/d/Slcr/S4/Extensions/CMake/SlicerBlockAdditionalLauncherSettings.cmake:97 (string):
  string sub-command REPLACE requires at least four arguments.
```

Offending code is 
``` cmake
  # External projects - library paths
  foreach(varname IN LISTS ${SUPERBUILD_TOPLEVEL_PROJECT}_EP_LABEL_LIBRARY_PATHS_LAUNCHER_BUILD)
    set(value ${${varname}})
    string(REPLACE "<CMAKE_CFG_INTDIR>" "\${CMAKE_CFG_INTDIR}" value ${value})
    list(APPEND EXTENSION_LIBRARY_PATHS_BUILD ${value})
  endforeach()
```

Do any of you guys know of a change in the Slicer level variable that might break this?

**Comment by Sunderlandkyl** [comment]
This looks to be the change in Slicer: https://github.com/Slicer/Slicer/commit/b1efab8a65c097621aad2a2eaf2ba1b17ebad212

There is only one variable in "inner_EP_LABEL_LIBRARY_PATHS_LAUNCHER_BUILD": "VP9_LIBRARY_PATHS_LAUNCHER_BUILD". The value  of VP9_LIBRARY_PATHS_LAUNCHER_BUILD is empty, causing the error in string(REPLACE ...).

**Comment by Sunderlandkyl** [comment]
I'm testing a fix now.
